version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    volumes:
      - $PWD/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: picklerick
      POSTGRES_USER: localdev
      POSTGRES_DB: fisforfood
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    hostname: fisforfood_adminer
    ports:
      - '8080:8080'
